config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'cocktails#home'
  resources :cocktails do
    resources :doses, only: %i[index new create]
    resources :reviews, only: [:new, :create]
    collection do
      get :healthy_cocktails
    end
  end
  resources :doses, only: %i[show edit update destroy]
  resources :ingredients
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  has_one_attached :photo
  validates :name, uniqueness: true
  validates :name, :photo, :category, presence: true
  
  def self.search(search)
    if search
      cocktail = Cocktail.find_by(name: search)
      if cocktail
        where(cocktail_id: cocktail)
      else
        @cocktails = Cocktail.all
      end
    else
      @cocktails = Cocktail.all
    end
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  has_one_attached :photo
  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_one_attached :photo
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true
  validates :name, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: %i[show edit update destroy healthy_coktail]

  def home
    @cocktails = Cocktail.last(3)
  end

  def healthy_cocktails
    @cocktails = Cocktail.where(category: 'Non-Alcohol')
  end

  def index
    @cocktails = Cocktail.where(category: 'Alcohol')
  end

  def show; end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit; end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :category, :description, :photo, :creator, :search)
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def index
    @doses = Dose.all
  end

  def show
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktails_path(@cocktail)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/cocktails/edit.html.erb
<div class="container">
  <h1>Recreate your cocktail</h1>
  <%= simple_form_for(@cocktail)  do |f| %>
    <%= f.input :name %>
    <%= f.input :category, :collection => %w[Alcohol Non-Alcohol] %>
    <%= f.input :description %><br>
    <%= f.input :creator, placeholder: "Please add your name" %><br>
    <%= f.input :photo, as: :file %><br>
    <%= f.submit "Add a cocktail", class: "btn btn-primary mt-2" %>
  <% end %>




  <div class="loading">
    <span><i class="fas fa-wine-bottle"></i></span>
    <span><i class="fas fa-wine-bottle"></i></span>
    <span><i class="fas fa-wine-bottle"></i></span>
    <div class="line"></div>
  </div>
  <%#= link_to "Add a the doses", new_cocktail_dose_path(@cocktail), type: "button", class: "btn btn-primary mt-2" %>
</div>

app/views/cocktails/healthy_cocktails.html.erb
<div class="bgimg">

    <%= cl_image_tag("comingsoon3_jtd1mm", width: 1510, height: 800, crop: :fill) %>


  <div class="middle">
    <h1 style="font-family: 'Londrina Solid', cursive; text-align: center; font-size: 55px">OUR NEW HEALTHY COCKTAIL RECIPES</h1>
    <h3 style="text-align: center; font-family: Pacifico, cursive;">COMING SOON </h3>
    <iframe src="http://free.timeanddate.com/countdown/i7nvxrqp/n1324/cf12/cm0/cu4/ct0/cs0/ca0/co0/cr0/ss0/cacfff/cpcfff/pct/tcfff/fs100/szw1200/szh506/iso2022-04-01T00:00:00/pd2" allowTransparency="true" frameborder="0" width="453" height="108"></iframe>

  </div>
</div>

app/views/cocktails/home.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" data-interval="8000">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <p class="auto_type">
        <span id="banner-typed-text"></span>
      </p>
      <img src="/assets/home_3.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/assets/home_2.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="/assets/home_1.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>




<div class="album text-muted">
  <div class="container">
    <div class="row-index row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-sm-12 col-md-4 ">
          <div class="card-index">
          <%= cl_image_tag cocktail.photo.key, height: 315, width: 350, crop: :fill %>
          <div>
            <strong class="card-text_index" style="font-family: 'Londrina Solid', cursive; color: #0E0000 "><%= link_to cocktail.name, cocktail_path(cocktail) %></strong>
            <!--          <a href="<%#= product_path(product) %>"><%#= image_tag("picture_holder")%><a>-->
            <p><%= cocktail.description %></p>
            <div class="card-foot">
              <div class="foot edit"><i class="fas fa-edit"><%= link_to "Edit me", edit_cocktail_path(cocktail) %></i>
              </div>
            </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-12">
      </div>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="cocktail_page">
<div class="navbar-cocktail">
<h1 style="font-family: 'Londrina Solid', cursive; ">List of cocktails</h1>
<div style="font-family: 'Pacifico', cursive;">
  <%= link_to "Add a new cocktail", new_cocktail_path, type: "button", class: "btn btn-primary mt-2" %>
</div>
</div>



  <div class="album text-muted">
  <div class="container">
    <div class="row-index row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-sm-12 col-md-4 ">
          <div class="card-index">
            <%= cl_image_tag cocktail.photo.key, height: 315, width: 323, crop: :fill%>
            <div>
              <strong class="card-text_index" style="font-family: 'Londrina Solid', cursive; color: #0E0000 "><%= link_to cocktail.name, cocktail_path(cocktail) %></strong>
              <!--          <a href="<%#= product_path(product) %>"><%#= image_tag("picture_holder")%><a>-->
              <p><%= cocktail.description %></p>
              <div class="card-foot">
                <div class="foot edit"><i class="fas fa-edit"><%= link_to "Edit me", edit_cocktail_path(cocktail) %></i>
                </div>
                <div class="foot edit">
                  <%= link_to "Give a review", new_cocktail_review_path(cocktail) %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-12">
      </div>
    </div>
  </div>
</div>


<!--<p> </p>-->
<!--<p> <%#= link_to "Delete", cocktail_path(cocktail), method: :delete, data: { confirm: "You sure?" } %></p>-->
<!--style="color: #0E0000; font-family: 'Pacifico', cursive;"-->
</div>

app/views/cocktails/new.html.erb
<div class="main-wrapper">
  <h1>New cocktail</h1>


  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Let's Start</button>

  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">New message</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for(@cocktail)  do |f| %>
            <%= f.input :name %>
            <%= f.input :category, :collection => %w[Alcohol Non-Alcohol] %>
            <%= f.input :description %><br>
            <%= f.input :creator, placeholder: "Please add your name" %><br>
            <%= f.input :photo, as: :file %><br>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Confirm", class: "btn btn-primary mt-2" %>
        </div>
          <% end %>
      </div>
    </div>
  </div>

  <div class="loading">
    <span><i class="fas fa-wine-bottle"></i></span>
    <span><i class="fas fa-wine-bottle"></i></span>
    <span><i class="fas fa-wine-bottle"></i></span>
    <div class="line"></div>
  </div>
  <%#= link_to "Add a the doses", new_cocktail_dose_path(@cocktail), type: "button", class: "btn btn-primary mt-2" %>
</div>

app/views/cocktails/show.html.erb
<div class='sample' id='sample'>

  <div class="show-container">
    <h1 style="text-align: center; font-family: 'Londrina Solid', cursive; font-size: 100px"><%= @cocktail.name.upcase %></h1>
    <div style="display: grid; grid-template-columns: 1fr 1fr;">
      <div class="image-container">
        <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
      </div>
      <div class="text-container">
        <div>
          <span>Category: <%= @cocktail.category %></span>
          <span>Created by: <%= @cocktail.creator %></span><br>
          <p><%= @cocktail.description %></p>
        </div>
        <div>
          <div>
            <table>
              <thead>
              <tr style="text-align: center; width: 30px">
                <th>Ingredient</th>
                <th>Doses</th>
                <th>Delete</th>
              </tr>
              </thead>
              <tbody>
              <tr>
                <% @cocktail.doses.each do |dose| %>
                  <td><%= dose.ingredient.name %></td>
                  <td><%= dose.description %></td>
                  <td>
                    <div class="foot delete">
                      <i class="fas fa-trash-alt"><%= link_to "Delete me", dose_path(dose), method: :delete, data: { confirm: "You sure?" } %></i>
                    </div>
                  </td>
                  </tr>
                <% end %>
                </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div>
    <div>
      <div class="foot edit"><i class="fas fa-magic"><%= link_to "more doses", new_cocktail_dose_path(@cocktail) %></i></div>
      <div class="foot edit"><i class="fas fa-edit"><%= link_to "edit me", edit_cocktail_path(@cocktail) %></i></div>
      <div class="foot edit"><i class="fas fa-cocktail"><%= link_to "more cocktails", cocktails_path %></i></div>
    </div>
    <div>
      <form id="form1" runat='server'>
        <i class="fas fa-file-pdf"><input style="display: inline-block;" type="button" value="Save this recipe" onclick="javascript:printDiv('sample')"/></i>
      </form>
    </div>
  </div>
</div>




<!--Javascript function to save data inside 'sample' div -->

<script language="javascript" type="text/javascript">
  function printDiv(divID) {
    var divElements = document.getElementById(divID).innerHTML;
    var oldPage = document.body.innerHTML;

    document.body.innerHTML =
      "<html><head><title></title></head><body>" +
      divElements + "</body>";

    window.print();

    document.body.innerHTML = oldPage;
  }
</script>

app/views/doses/new.html.erb
<div class="container">
  <h1>New dose for <%= @cocktail.name %></h1>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient, collection: Ingredient.order(:name), prompt: "Choose an ingredient" %>
    <%= f.submit "Add an ingredient", class: "btn btn-primary mt-2" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.scss">-->
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.scss">-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Londrina+Solid:wght@400;900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<!--    <link rel="stylesheet" href="node_modules/@glidejs/glide/dist/css/glide.core.min.css">-->
<!--    <link rel="stylesheet" href="node_modules/@glidejs/glide/dist/css/glide.theme.min.css">-->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "components/navbar" %>
    <%= yield %>
    <%= render "components/footer" %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= simple_form_for @review do |f| %>
        <%= f.input :content %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
        <%= f.submit "Send your review" %>
      <% end %>
    </div>
  </div>
</div>